### PR TITLE
Fix in order to allow multiple input shapes.

### PR DESCRIPTION
**Pull request by sergeykolychev**
The MXPredCreate* c++ functions have a bug that prevents them from accepting more than one input shape.
Consequently the comments for these functions are pretty confusing and led to an incorrect implementation of this functionality in this file. 
This is the fix for the mxnet code, just fyi.
https://github.com/dmlc/mxnet/pull/5539
@songtianyi

### CODE REVIEW

**Comment by sergeykolychev** [comment]
@songtianyi actually on second thought it's possible to get the same results without changing the c++ side, by providing the shapeIdx as {0,2,4} for two two-dimensional shapes.

**Comment by songtianyi** [comment]
@sergeykolychev 
Hi,
Could you add one test case for your PR. To make sure it will work with future commits.

**Comment by sergeykolychev** [comment]
I am pretty new to golang, so I am not familiar with established practices of the testing in Go.
I can give you a symbol json tomorrow that will work with my fix and fail without, will that suffice ?

**Comment by sergeykolychev** [comment]
@songtianyi Here you go, this simple test.go will work on my branch and will fail on your master
because mxnet needs to know the shape of the softmax_label however current code is incorrectly 
delivers this info.
your current code is putting in shapeIdx as {0,2,2} but mxnet is expecting {0,2,4} which is what my fix does.
Here is the code that is expecting the shapeIdx to be in this format (it took me a while to track that :-))
https://github.com/dmlc/mxnet/blob/master/src/c_api/c_predict_api.cc#L151

**Pull request merged**
